# Generated by Django 4.2.7 on 2023-11-12 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unsecu', '0002_content_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
