# Generated by Django 4.2.7 on 2023-11-12 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unsecu', '0003_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={},
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
